

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8


mybatis:
  configLocation: classpath:/MyBatis-conf.xml
  mapperLocations:
    - classpath:/mapper/*.xml
logging:
  level:
    root: debug #调试的时候使用debug  trace打印更多日志
#  pattern:
# 打印行号
#    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M:%L - %msg%n'
